### ISSUE TITLE
AddOn doesn't work with Thunderbird v.60.3.0

### ISSUE THREAD

**Issue by jwsp1** [ysard/mintrayr#17]
Every time I close Thunderbird, the program doesn't minimize to system tray but closes completely. I've double checked the settings - everything should be correct and I've already tried different settings...

OS: Windows 10 (Build 17134)
Thunderbird version 60.3.0

**Comment by Dtrieb** [comment]
Didn't show a Tray Symbol, TB didn't go in the Sys Tray.
Win 7 - TB: 60.3.0 (32-Bit)

**Comment by soulhunter123** [comment]
+1

**Comment by sagamusix** [comment]
I found that changing the config value `extensions.mintrayr.minimizeon` from the default of `1` to `2` makes the extension on a machine where the previous MinimizeToTray addon was not installed.

**Comment by ysard** [comment]
@jwsp1 : Thank you for your report, i will try on Windows as soon as possible, maybe the correct signal emitted on GNU systems is not the same on Windows.

@sagamusix :
Indeed, it is the option that make the addon sensitive to the closing event.
0 = Never
1 = When minimizing
2 = Instead of closing
3 = Instead of closing and when minimizing
But you can not access the configuration via the "Tools / add-ons options" menu?
Does this manual modification allow you to make Thunderbird responsive to the closing event on Windows?

**Comment by Dtrieb** [comment]
@ysard:

No it makes no change if you user any of the numbers. I try 1,2,3 and it doesn't work for me.

**Comment by ysard** [comment]
@sagamusix 
In fact the presence of this button in the addons page is possible (although recent in Thunderbird) but I am faced with a problem of size of the window that I can not fix for the moment. I note the need to fix this.

@jwsp1 & @Dtrieb:
Ok The addon is not functional for both of you, whatever the configuration (minimization / closure), and you are on Windows 10 and 7. Until then there was a context menu problem on Windows 10 only but the addon seemed to work on Windows :/

**Comment by Dtrieb** [comment]
Crazy on my laptop in the uni (Win7) it works! 🤔

**Comment by jwsp1** [comment]
Yay! It's working with the latest update v1.4.6. Thank you 👍
