### ISSUE TITLE
Open Message In New Window Can Never Close

### ISSUE THREAD

**Issue by drkui** [ysard/mintrayr#19]
I think the expected behavior is minimizing to tray for the main Thunderbird application only, I don't think it's supposed to apply to messages opened in a new window. 

As it is now, there's a bug where messages in windows can never close and are minimized to tray because of the add-on.

**Comment by ysard** [comment]
Hi, If you check "Minimize to tray", then "Use for Message windows" or "Use for Write windows", then the expected behavior is that the addon will listen for the minimization and/or closing events of the message writing windows.
In your case, I think that only "Use for Messenger windows" should be checked.

**Comment by drkui** [comment]
Hi,

Wow, I didn't even know there were options for that until now. I don't recall seeing that in the original MinimizeToTray plugin.

Thanks for your help!
