### ISSUE TITLE
No additional/different tray icon for new messages

### ISSUE THREAD

**Issue by xonfour** [ysard/mintrayr#21]
**Describe the bug**
I'm using 1.4.6 with TB 60.3.0 (64Bit) and Manjaro/KDE Plasmashell. I get the tray icon (although in low resolution) but it doesn't change for new mail. Also there is no addition second tray icon (as indicated in one of the comments at Mozilla).

**Expected behavior**
I would love to get back the permanent notification of new mail as a tray icon.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux, KDE Plasmashell 5.14.3
 - Thunderbird Version 60.3.0 64Bit

**Comment by ysard** [comment]
Hello, actually I misunderstood the comment about the change of icon on AMO.
I close this issue because this addon has never offered this feature, but it is indeed something very interesting and unavoidable for a future project :)

**Comment by monte-monte** [comment]
@ysard so there won't be a way to indicate new messages in tray with this extension?

**Comment by ysard** [comment]
With this extension no; at least not before I developed an extension for Thunderbird Beta with this type of feature.
For the moment, to my knowledge there is no WebExtension API to capture this kind of event. The use of old API is possible but it is time poorly invested since they are destined to disappear in the medium term.
However, if no WebExtension API is developed, the backport of a code will still be possible here.
