### ISSUE TITLE
Key Shortcut

### ISSUE THREAD

**Issue by markusb68** [ysard/mintrayr#23]
Is it possible to add the possibility to define a key shortcut (like WIN-y) for maximizing and closing to tray?

**Comment by ysard** [comment]
Hi, this shortcut will be available only on Windows and MacOS and only for a minimization to tray (maximization is driven by the desktop/OS manager).
For GNU/Linux OS the choice of the Ctrl modifier seems risky to me so I don't implement it yet.

**Comment by markusb68** [comment]
Hmm, sad to hear. I'm looking for a [Thunderbird-Tray](https://sourceforge.net/projects/tbtray/) replacement. TB-Tray could minimize to tray and also maximize with a system wide shortcut.

**Comment by ysard** [comment]
Here are some explanations.

With JavaScript (the language used for the addon), under Windows and Mac the meta key ("Windows" or "Command") is a modifier that can be used in combination with another key.
On Linux with JavaScript, this key is recognized as a separate key and cannot be used in combination with another key.

The use of the Ctrl key is already often reserved for actions such as Ctrl + Y (Redo), Ctrl + Z (Undo). So I don't recommend its hard-coded implementation in an addon because it could disrupt Thunderbird's working.

In addition, window minimization/maximization actions are managed by the desktop manager more than the software itself.
Under Windows it can be complex to remap key combinations for that, which is why I accepted the proposal, but under Linux it is excessively simple.
Here is an example under KDE:
![image](https://user-images.githubusercontent.com/14988285/49450948-63904600-f7de-11e8-86cb-0e4ae3f88255.png)



Going through this manager will also prevent you from overwriting an existing system shortcut.
