### ISSUE TITLE
F9 Does Not Minimize Thunderbird

### ISSUE THREAD

**Issue by qcybb** [ysard/mintrayr#34]
Pressing F9 does not minimize Thunderbird.

Also, is it possible not to display the "Minimize to tray F9" text in the file menu? I'm used to closing applications by clicking on file menu / exit - and the "exit" is usually at the very bottom.  I find myself clicking on your entry now because it sits at the bottom (instead of "Exit").

Environment :
Windows 10
ThunderBird 60.5.3
MinimizeToTray Reanimated v1.4.9

**Comment by ysard** [comment]
Hi, F9 problem should be fixed in the next release.
It is replaced by Ctrl+Maj+Y or Meta+Y (meta is the Windows key).

I keep the presence of the entry in the menu for the moment because it can be used by other people and I can not easily create an option to display it in this addon but I keep the idea in memory .
The position of this entry is due to an alphabetical order, I can not do much more here.
